// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrxbjvhihndoslkghage.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyeGJqdmhpaG5kb3Nsa2doYWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzU3NDksImV4cCI6MjA2OTk1MTc0OX0.-LKkVGn5zGfr7WI7FMmLEkxEvW6JcK8_lFUalrlr-DY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});